# Generated by Django 5.0.3 on 2024-12-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='horario_id',
            new_name='horario',
        ),
    ]
