# Generated by Django 5.0.3 on 2024-12-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGE', '0002_rename_horario_id_reserva_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
